runtime: python39
entrypoint: gunicorn -b :$PORT contacts_app.wsgi:application

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DJANGO_SETTINGS_MODULE: "contacts_app.settings"
  DEBUG: "False"

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always 